"""Alembic env for a wallow project. Generated by `wallow init`.

This env loads the wallow schema (TOML) and hands its dynamically-built
SQLAlchemy metadata to Alembic for autogenerate. The schema path comes
from the `wallow_schema` main option in alembic.ini, resolved relative to
the alembic.ini directory.

`render_as_batch=True` is required for SQLite, which can't ALTER TABLE to
drop or modify constraints — Alembic emulates them via copy-and-rename
when batch mode is on.
"""

from __future__ import annotations

from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

import wallow

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

_ini_dir = (
    Path(config.config_file_name).resolve().parent
    if config.config_file_name
    else Path.cwd()
)
_schema_rel = config.get_main_option("wallow_schema", "wallow.toml")
_schema_path = (_ini_dir / _schema_rel).resolve()

# Resolve a relative sqlite URL against the ini's directory so the project
# is portable: `sqlite:///runs.db` means "runs.db next to alembic.ini".
_url = config.get_main_option("sqlalchemy.url") or ""
if _url.startswith("sqlite:///"):
    _rest = _url[len("sqlite:///"):]
    if _rest and _rest != ":memory:" and not Path(_rest).is_absolute():
        config.set_main_option(
            "sqlalchemy.url", f"sqlite:///{(_ini_dir / _rest).resolve()}"
        )

schema = wallow.load_schema(_schema_path)
target_metadata = schema.Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
