"""initial schema

Revision ID: 25d857902f9d
Revises: 
Create Date: 2026-04-28 00:37:20.315850

NOTE: wallow migrations are immutable once applied to any environment.
If you need to change something in this file BEFORE applying it, edit
freely. After applying, generate a new revision instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d857902f9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cell_k', sa.Integer(), nullable=False),
    sa.Column('cell_sigma', sa.Float(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('git_commit', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('wall_clock_sec', sa.Float(), nullable=True),
    sa.Column('val_loss', sa.Float(), nullable=True),
    sa.Column('val_accuracy', sa.Float(), nullable=True),
    sa.Column('artifacts_dir', sa.String(), nullable=True),
    sa.Column('structural_traj', sa.JSON(), nullable=True),
    sa.Column('discovered_T', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'cell_k', 'cell_sigma', 'generation', 'seed', name='uq_runs_identifying')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_cell_k'), ['cell_k'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_cell_sigma'), ['cell_sigma'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_generation'), ['generation'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_git_commit'), ['git_commit'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_seed'), ['seed'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_val_accuracy'), ['val_accuracy'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_val_loss'), ['val_loss'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_val_loss'))
        batch_op.drop_index(batch_op.f('ix_runs_val_accuracy'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_runs_seed'))
        batch_op.drop_index(batch_op.f('ix_runs_host'))
        batch_op.drop_index(batch_op.f('ix_runs_git_commit'))
        batch_op.drop_index(batch_op.f('ix_runs_generation'))
        batch_op.drop_index(batch_op.f('ix_runs_cell_sigma'))
        batch_op.drop_index(batch_op.f('ix_runs_cell_k'))
        batch_op.drop_index(batch_op.f('ix_runs_candidate_id'))

    op.drop_table('runs')
    # ### end Alembic commands ###
