"""add uuid column

Revision ID: c1a1abeffa7f
Revises: 2737e4057e14
Create Date: 2026-04-29 23:56:25.777352

NOTE: wallow migrations are immutable once applied to any environment.
If you need to change something in this file BEFORE applying it, edit
freely. After applying, generate a new revision instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a1abeffa7f'
down_revision: Union[str, Sequence[str], None] = '2737e4057e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The autogenerated form was `add_column(..., nullable=False)`, but
    # NOT NULL can't be added to a non-empty table without a backfill. We
    # add the column nullable, populate it with random 12-char hex (SQLite's
    # randomblob(6) → hex = 12 chars, matching wallow's uuid format), then
    # tighten the constraint and create the unique index.
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=12), nullable=True))
    op.execute("UPDATE runs SET uuid = lower(hex(randomblob(6))) WHERE uuid IS NULL")
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False)
        batch_op.create_index(batch_op.f('ix_runs_uuid'), ['uuid'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
