"""add warmup_steps

Revision ID: 2737e4057e14
Revises: 25d857902f9d
Create Date: 2026-04-28 00:37:45.461746

NOTE: wallow migrations are immutable once applied to any environment.
If you need to change something in this file BEFORE applying it, edit
freely. After applying, generate a new revision instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2737e4057e14'
down_revision: Union[str, Sequence[str], None] = '25d857902f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warmup_steps', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_runs_identifying'), type_='unique')
        batch_op.create_unique_constraint('uq_runs_identifying', ['candidate_id', 'cell_k', 'cell_sigma', 'generation', 'seed', 'warmup_steps'])
        batch_op.create_index(batch_op.f('ix_runs_warmup_steps'), ['warmup_steps'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_warmup_steps'))
        batch_op.drop_constraint('uq_runs_identifying', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_runs_identifying'), ['candidate_id', 'cell_k', 'cell_sigma', 'generation', 'seed'])
        batch_op.drop_column('warmup_steps')

    # ### end Alembic commands ###
